server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: false
    #是否从EurekaServe抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true 才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #设置与Eurke srever交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/


feign:
  hystrix:
    enabled: true


#设置feign客户端得超时时间 （Openfeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常得情况下，两端链接所用得时间
  ReadTimeout: 5000
  #指的是建立链接后从服务器读取到可用资源所用得时间
  ConnectTimout: 5000

logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.demo.springcloud.service.PaymentFeignService: debug